/*
 * sfnedit/lang.c
 *
 * Copyright (C) 2019 bzt (bztsrc@gitlab)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * @brief Multilanguage support
 *
 */

#include "lang.h"

/**
 * Translations
 */
char *dict[NUMLANGS][NUMTEXTS + 1] = {
    {
        "en",

        "memory allocation error",
        "unable to open display",
        "unable to load font",
        "unable to save font",
        "bad glyph size",

        "Measuring bounding box",
        "Querying outlines",
        "Querying all kerning combinations",
        "Quantizing image",
        "Reading file",
        "Reading bitmap",
        "Reading tall pixel map",
        "Reading wide pixel map",
        "Generating fragments",
        "Compressing fragments",
        "Serializing fragments",
        "Writing character map",
        "Writing file",
        "Rasterizing",
        "Vectorizing",
        "Copying to clipboard",

        "Help:",
        "If anytime you feel lost, press [F1]. UNICODE database:",
        "Permission is hereby granted, free of charge, to any person",
        "obtaining a copy of this software and associated documentation",
        "files (the \"Software\"), to deal in the Software without",
        "restriction, including without limitation the rights to use, copy,",
        "modify, merge, publish, distribute, sublicense, and/or sell copies",
        "of the Software, and to permit persons to whom the Software is",
        "furnished to do so, subject to the following conditions:",
        "",
        "The above copyright notice and this permission notice shall be",
        "included in all copies or substantial portions of the Software.",

        "About",
        "Load Font",
        "Save Font",
        "Properties",
        "Blocks coverage",
        "Characters",
        "Metrics",
        "Layers",
        "Kerning",
        "Color Picker",

        "Name",
        "Size",
        "Modified",
        "Range:",
        "replace glyphs",
        "Import",
        "Save",
        "Save modified font?",
        "Drop all glyphs and start anew?",
        "No",
        "Yes",
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Yesterday",
        "Just now",
        "%d minutes ago",
        "%d hours ago",
        "an hour ago",

        "Type",
        "Unique name",
        "Family name",
        "Subfamily",
        "Font revision",
        "Manufacturer",
        "License",
        "Serif",
        "SansSerif",
        "Decorative",
        "Monospace",
        "Handwriting",
        "Bold",
        "Italic",
        "usrdef1",
        "usrdef2",

        "Show uncovered blocks",
        "Coverage",
        "UNICODE Block",

        "Vectorize font",
        "Unable to vectorize, compiled without potrace",
        "Rasterize font at given size",
        "Zoom out, smaller glyphs",
        "Zoom in, larger glyphs",
        "Copy and delete glyphs",
        "Copy glyphs",
        "Paste glyphs",
        "Delete glyphs",
        "Search results",
        "undefined by UNICODE",
        "SSFN LIGATURE",
        "Selected",

        "UTF-8 copied to clipboard",
        "Glyph's width",
        "Glyph's height",
        "Baseline position (global)",
        "Underline position (global)",
        "Horizontal overlap",
        "Horizontal advance",
        "Vertical advance",
        "Right-to-Left advance",
        "Up-to-Down advance",
        "Left-to-Right advance",
        "Reposition glyph",
        "Make italic",
        "Make unitalic",
        "Flip horizontally",
        "Flip vertically",
        "Recalculate dimensions",
        "Drop all layers",

        "Zoom out layer",
        "Zoom in layer",
        "Copy and delete layer",
        "Copy layer",
        "Paste layer",
        "Add a new vector layer",
        "Add a new bitmap layer",
        "Add a new pixel map layer",
        "Change foreground color",
        "Color picker",
        "Drop current layer",

        "Delete kerning pair",

        "OK",

        "There's one main window per font with it's properties and character table.",
        "You can open one glyph window per character.",
        "Keys available at all times\n[Esc]\tclose current window\n[Tab]\tnext field\n[Shift]+[Tab]\tprevious field\n[Ctrl]+[S]\tquick save\n[Shift]+[Ctrl]+[S]\tsave as",
        "In this window you can import a range of glyphs from various font formats.",
        "This is where you can specify the filename and save your modified font.",
        "Font type is used with ssfn_select(). Unique name is the string to match with SSFN_FAMILY_BYNAME.",
        "Here you have an overview of which UNICODE blocks are covered by the font.\nCoverage can be greater than 100% when glyphs are specified for undefined characters.",
        "Full character table with all glyphs in the font. You can convert between scalable and bitmap\nglyphs, and select and manipulate ranges.\nBindings:\n[wheel]/[up]/[down]\tscroll table\n[leftclick]\topen glyph window\n[left drag]\tselect range\n[right click]\tcopy'n'paste selected range to position\n[Ctrl]+[click]\tcopy UTF-8 to clipboard\n[Ctrl]+[A]\tselect all glyphs\n[Ctrl]+[X]\tcut selected range\n[Ctrl]+[C]\tcopy selected range\n[Ctrl]+[V]\tpaste range starting from selection\n[Del]/[Backspace]\tdelete selected glyphs",
        "Here you can specify metrics (width, height, advances, overlap, etc.) and use different\ntransformations on the glyph.\nKeybindings:\n[up]/[down]\n[left]/[right]\trotate/move glyph around\n[H]\tflip horizontally\n[V]\nflip vertically",
        "Edit each glyph layer individually.\n[PgUp]\tprevious layer\n[PgDn]\tnext layer\n[Ctrl]+[X]\tcut (copy and delete) selected layer\n[Ctrl]+[C]\tcopy selected layer\n[Ctrl]+[V]\tpaste as new layer(s)\n[Del]\tdelete selected layer\n[Backspace]\tremove last contour command from path\n[left btn click]\ttoggle point on bitmap/pixel layers\n[left btn drag]\tmove layer / move points on contour layers\n[Shift]+[left btn]\tadd a line to contour\n[Ctrl]+[left btn]\tadd a cubic Bezier curve\n[Ctrl]+[right btn]\tadd a quadratic Bezier curve",
        "Specify different advances for character combinations.\n[left]/[right]\tmodify horizontal advance\n[up]/[down]\tmodify vertical advance",
        "Edit the color map of the font and pick a color for the layer to use."
    },
    {
        "hu",

        "nem tudok memóriát foglalni",
        "nem lehet megnyitni a képernyőt",
        "nem tudom betölteni",
        "nem tudom lementeni",
        "hibás glif méret",

        "Határoló téglalap mérése",
        "Körvonalak lekérése",
        "Kernelő kombinációk lekérése",
        "Kép kvantálása",
        "Fájl olvasása",
        "Bitmap olvasása",
        "Magas kép olvasása",
        "Széles kép olvasása",
        "Fragmensek generálása",
        "Fragmensek tömörítése",
        "Fragmensek formázása",
        "Karaktertérkép kiírása",
        "Fájl kiírása",
        "Raszterizálása",
        "Vektorizálás",
        "Vágólapra másolás",

        "Súgó:",
        "Ha bármikor elvesznél, üss [F1]-et. UNICODE adatbázis:",

        "Aki hozzáfér a programhoz és a dokumentációjához (továbbiakban",
        "\"Szoftver\"), az ingyen és korlátozás nélkül felhasználhatja,",
        "alkalmazhatja, feldolgozhatja, terjesztheti, lemásolhatja,",
        "kiadhatja, továbbadhatja, továbbértékesítheti a Szoftvert,",
        "és ezeket a lehetőségek az új felhasználóknak is továbbadja,",
        "de csak akkor, amennyiben az alábbi feltételek teljesülnek:",
        "",
        "A jogtulajdonos készítőt, a fenti licensz és felhatalmazás szövegét fel",
        "kell tüntentni a Szoftver minden egyes teljes vagy részleges másolatán.",
        "",

        "Névjegy",
        "Font betöltése",
        "Font lementése",
        "Tulajdonságok",
        "Blokk lefedettség",
        "Karakterek",
        "Metrikák",
        "Rétegek",
        "Kernelés",
        "Színválasztó",

        "Név",
        "Méret",
        "Módosítva",
        "Szűkítés:",
        "glifek lecserélése",
        "Importál",
        "Lement",
        "Elmentsem a módosított fontot?",
        "Minden glifet eldobjak?",
        "Nem",
        "Igen",
        "Vasárnap",
        "Hétfő",
        "Kedd",
        "Szerda",
        "Csütörtök",
        "Péntek",
        "Szombat",
        "Tegnap",
        "Épp most",
        "%d perce",
        "%d órája",
        "egy órája",

        "Típus",
        "Egyedi név",
        "Családnév",
        "Alcsalád",
        "Font revízió",
        "Készítő",
        "Licensz",
        "Serif",
        "SansSerif",
        "Dekoratív",
        "Monospace",
        "Kézírás",
        "Félkövér",
        "Dőlt",
        "usrdef1",
        "usrdef2",

        "Üres blokkok mutatása",
        "Lefedettség",
        "UNICODE Blokk",

        "Font vektorizálás",
        "Nem lehet vektorizálni, potrace nélkül lett fordítva",
        "Raszterizálás adott méretben",
        "Kicsinyítés",
        "Nagyítás",
        "Glifek másolása és törlése",
        "Glifek másolása",
        "Glifek beillesztése",
        "Glifek törlése",
        "Keresés eredménye",
        "UNICODE nem definiálta",
        "SSFN LIGATURE",
        "Kiválasztva",

        "UTF-8 a vágólapra másolva",
        "Glif szélessége",
        "Glif magassága",
        "Alapvonal poziciója (globális)",
        "Aláhúzás poziciója (globális)",
        "Horizontális átfedés",
        "Horizontális léptetés",
        "Vertikális léptetés",
        "Jobbról-balra léptetés",
        "Fentről-le léptetés",
        "Balról-jobbra léptetés",
        "Glif pozicionálása",
        "Dőltté tesz",
        "Kiegyenesít",
        "Horizontálisan tükrözés",
        "Vertikálisan tükrözés",
        "Metrikák újraszámítása",
        "Minden réteg eldobása",

        "Réteg kicsinyítés",
        "Réteg nagyítás",
        "Réteg másolása és törlése",
        "Réteg másolása",
        "Réteg beillesztése",
        "Új vektorréteg hozzáadása",
        "Új bitmapréteg hozzáadása",
        "Új pixelréteg hozzáadása",
        "Előtér színének változtatása",
        "Pipetta",
        "Aktuális réteg eldobása",

        "Kerneléspár eldobása",

        "OK",

        "Fontonként egy fő ablak van, a tulajdonságokkal és a karakter táblázattal.",
        "Karakterenként egy glif ablak lehet nyitva.",
        "Mindig elérhető kombinációk:\n[Esc]\taktív ablak bezárása\n[Tab]\tkövetkező mező\n[Shift]+[Tab]\telőző mező\n[Ctrl]+[S]\tgyorsmentés\n[Shift]+[Ctrl]+[S]\tmentés mint",
        "Ebben az ablakban lehet glifeket importálni különféle formátumú font fájlokból.",
        "Itt adhatod meg a fájlnevet és mentheted el a módosított fontot.",
        "A font típusa használatos az ssfn_select()-nél. Az itt beállított egyedi névre keres az\nSSFN_FAMILY_BYNAME megadásakor.",
        "Itt egyben láthatod, mely UNICODE blokkat fedi le a font.\nA lefedettség lehet 100%-nál nagyobb, ha nem definiált karaktereknek is van glifje.",
        "Teljes karaktertábla a font összes glifjével. Konvertálhatsz, valamint tartományokat jelölhetsz\nki és módosíthatsz.\nHozzárendelések:\n[görgő]/[fel]/[le]\tszkrollozás\n[balklikk]\tglif ablak megnyitása\n[balgomb húzás]\tkijelölés\n[jobbklikk]\tmásolás és beillesztés a pozícióra\n[Ctrl]+[balklikk]\tUTF-8 vágólapra\n[Ctrl]+[A]\tmindent kijelöl\n[Ctrl]+[X]\tkivágás\n[Ctrl]+[C]\tmásolás\n[Ctrl]+[V]\tbeillesztés a kijelöléstől kezdve\n[Del]/[Backspace]\tkijelölt glifek törlése",
        "Itt lehet megadni a metrikákat (szélesség, magasság, léptetés,\nátfedés, stb.) és különböző transzformációkat alkalmazni a glifen.\nGombkombinációk:\n[fel]/[le]\n[balra]/[jobbra]\tglif körbetekerése/elcsúsztatása\n[H]\thorizontális tükrözés\n[V]\tvertikális tükrözés",
        "Glifrétegek szerkesztése.\n[PgUp]\telőző réteg\n[PgDn]\tkövetkező réteg\n[Ctrl]+[X]\taktív réteg kivágása\n[Ctrl]+[C]\taktív réteg másolása\n[Ctrl]+[V]\tbeillesztés új rétegekre\n[Del]\taktív réteg törlése\n[Backspace]\tutolsó kontúrparancs törlése\n[balgomb klikk]\tpont kapcsolgatása bitmap/pixel rétegen\n[balgomb húzás]\tréteg / kontúrpont mozgatása\n[Shift]+[balgomb]\tvonal hozzáadása a kontúrhoz\n[Ctrl]+[balgomb]\tköbív hozzáadása\n[Ctrl]+[jobbgomb]\tnégyzetív hozzáadása",
        "Karakterkombinációnkénti léptetés megadása.\n[balra]/[jobbra]\thorizontális léptetés módosítása\n[fel]/[le]\tvertikális léptetés módosítása",
        "Színtérkép szerkesztése és a réteg színének kiválasztása."
    }
};
